export const SITE_TITLE = 'DDEV';
export const SITE_DESCRIPTION = 'Docker-based local PHP development environments.';
export const GITHUB_REPO = 'ddev/ddev';
export const GITHUB_URL = 'https://github.com/ddev/ddev';
export const GITHUB_ISSUES_URL = 'https://github.com/ddev/ddev/issues';
export const DOCUMENTATION_URL = 'https://ddev.readthedocs.io/';
export const DISCORD_URL = 'https://discord.gg/hCZFfAMc5k';
export const EMAIL_URL = "mailto:support%40ddev.com"
export const COPYRIGHT_HOLDER = 'DDEV Foundation'
export const MASTODON_URL = 'https://fosstodon.org/@ddev'
export const X_URL = 'https://twitter.com/search?q=%23ddev&src=typd&f=live'
export const ORG_STREET = '848 Montclair Dr'
export const ORG_CITY = 'Palisade'
export const ORG_STATE = 'Colorado'
export const ORG_POSTAL_CODE = '97702'
export const ORG_COUNTRY = 'US'
export const ORG_NAME = 'DDEV Foundation'
export const ORG_EMAIL = 'support@localdev.foundation'
export const ORG_PHONE = '(970) 462-7450'
export const ORG_FOUNDED = '2021-09-02'
export const ORG_SAME_AS = ["https://github.com/ddev", "https://localdev.foundation"]
export const BLOG_DESCRIPTION = `Posts about DDEV, Docker, and local development.`
